name: depoly a java application
on: push
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: check  out the code
     uses: actions/checkout@v2
   - name: setup java
     uses: actions/setup-java@v4
     with:
        distribution: temurin
        java-version: '17'
        cache: maven

   - name: Build with Maven
     run: mvn clean package
     working-directory: my-java-app

   - name: Run the app
     run: java -cp target/my-java-app-1.0.0.jar com.example.App
     working-directory: my-java-app
  
